version: '3.9'
services:
  elasticsearch:
    container_name: els
    #image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0-arm64
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    ports:
      - 9200:9200
    volumes:
      - ./elasticsearch-data/data:/usr/share/elasticsearch/data
    environment: 
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
      - discovery.type=single-node
    restart: unless-stopped
    networks:
      - net-elk
  kibana:
    container_name: kibana
    #image: docker.elastic.co/kibana/kibana:8.7.0-arm64
    image: docker.elastic.co/kibana/kibana:8.7.0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
    restart: unless-stopped
    networks:
      - net-elk

networks:
  net-db:
    name: net-db
    driver: bridge
  net-elk:
    name: net-elk
    driver: bridge
  net-message-queue:
    name: net-message-queue
    driver: bridge
  net-app:
    name: net-app
    driver: bridge