version: '3.9'
services:
  postgresdb:
    image: postgres
    #restart: unless-stopped
    container_name: postgresdb
    environment:
      - POSTGRES_USER: ${POSTGRESQL_USER}
      - POSTGRES_PASSWORD: ${DB_PASSWORD}
      - PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres-data/data:/var/lib/postgresql/data
    networks:
      - net-db
    ports:
      - 5432:5432

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    #restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: huynhquocbuu@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    volumes:
       - ./pgadmin4-data:/var/lib/pgadmin
    ports:
      - 9082:80
    networks:
      - net-db
      
  keycloak:
    image: bitnami/keycloak
    #restart: unless-stopped
    depends_on:
      - postgresdb
    container_name: bitnami_keycloak
    environment:
      #- KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_DATABASE_VENDOR: postgres
      - KEYCLOAK_DATABASE_HOST: postgresdb
      - KEYCLOAK_DATABASE_NAME: ${KEYCLOAK_DB}ÃŸ
      - KEYCLOAK_DATABASE_USER: ${POSTGRESQL_USER}
      - KEYCLOAK_DATABASE_PASSWORD: ${DB_PASSWORD}
      - KEYCLOAK_ADMIN_USER: ${KEYCLOAK_USER}
      - KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
    ports:
      - 9086:8080
      #- 8787:8787
    volumes:
        #- ./keycloak-data/import:/temp
        - ./keycloak-data/themes:/opt/bitnami/keycloak/themes
    networks:
      - net-db

networks:
  net-db:
    name: net-db
    driver: bridge
  net-elk:
    name: net-elk
    driver: bridge
  net-message-queue:
    name: net-message-queue
    driver: bridge
  net-app:
    name: net-app
    driver: bridge